nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  "@tanstack/router-devtools-core@*":
    peerDependenciesMeta:
      solid-js:
        optional: true
  "ts-node@*":
    dependencies:
      "@types/node": "*"