/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

import { Route as rootRouteImport } from './routes/__root';
import { Route as AboutNotLazyRouteImport } from './routes/aboutNotLazy';
import { Route as IndexRouteImport } from './routes/index';
import { Route as TodoExampleTodoidRouteImport } from './routes/todoExample/$todoid';

const AboutLazyRouteImport = createFileRoute('/about')();
const TodoExampleIndexLazyRouteImport = createFileRoute('/todoExample/')();
const BoardExampleIndexLazyRouteImport = createFileRoute('/boardExample/')();

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route));
const AboutNotLazyRoute = AboutNotLazyRouteImport.update({
  id: '/aboutNotLazy',
  path: '/aboutNotLazy',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const TodoExampleIndexLazyRoute = TodoExampleIndexLazyRouteImport.update({
  id: '/todoExample/',
  path: '/todoExample/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/todoExample/index.lazy').then((d) => d.Route));
const BoardExampleIndexLazyRoute = BoardExampleIndexLazyRouteImport.update({
  id: '/boardExample/',
  path: '/boardExample/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/boardExample/index.lazy').then((d) => d.Route));
const TodoExampleTodoidRoute = TodoExampleTodoidRouteImport.update({
  id: '/todoExample/$todoid',
  path: '/todoExample/$todoid',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/aboutNotLazy': typeof AboutNotLazyRoute;
  '/about': typeof AboutLazyRoute;
  '/todoExample/$todoid': typeof TodoExampleTodoidRoute;
  '/boardExample': typeof BoardExampleIndexLazyRoute;
  '/todoExample': typeof TodoExampleIndexLazyRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/aboutNotLazy': typeof AboutNotLazyRoute;
  '/about': typeof AboutLazyRoute;
  '/todoExample/$todoid': typeof TodoExampleTodoidRoute;
  '/boardExample': typeof BoardExampleIndexLazyRoute;
  '/todoExample': typeof TodoExampleIndexLazyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/aboutNotLazy': typeof AboutNotLazyRoute;
  '/about': typeof AboutLazyRoute;
  '/todoExample/$todoid': typeof TodoExampleTodoidRoute;
  '/boardExample/': typeof BoardExampleIndexLazyRoute;
  '/todoExample/': typeof TodoExampleIndexLazyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/aboutNotLazy'
    | '/about'
    | '/todoExample/$todoid'
    | '/boardExample'
    | '/todoExample';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/aboutNotLazy' | '/about' | '/todoExample/$todoid' | '/boardExample' | '/todoExample';
  id:
    | '__root__'
    | '/'
    | '/aboutNotLazy'
    | '/about'
    | '/todoExample/$todoid'
    | '/boardExample/'
    | '/todoExample/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutNotLazyRoute: typeof AboutNotLazyRoute;
  AboutLazyRoute: typeof AboutLazyRoute;
  TodoExampleTodoidRoute: typeof TodoExampleTodoidRoute;
  BoardExampleIndexLazyRoute: typeof BoardExampleIndexLazyRoute;
  TodoExampleIndexLazyRoute: typeof TodoExampleIndexLazyRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/aboutNotLazy': {
      id: '/aboutNotLazy';
      path: '/aboutNotLazy';
      fullPath: '/aboutNotLazy';
      preLoaderRoute: typeof AboutNotLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/todoExample/': {
      id: '/todoExample/';
      path: '/todoExample';
      fullPath: '/todoExample';
      preLoaderRoute: typeof TodoExampleIndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/boardExample/': {
      id: '/boardExample/';
      path: '/boardExample';
      fullPath: '/boardExample';
      preLoaderRoute: typeof BoardExampleIndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/todoExample/$todoid': {
      id: '/todoExample/$todoid';
      path: '/todoExample/$todoid';
      fullPath: '/todoExample/$todoid';
      preLoaderRoute: typeof TodoExampleTodoidRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutNotLazyRoute: AboutNotLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  TodoExampleTodoidRoute: TodoExampleTodoidRoute,
  BoardExampleIndexLazyRoute: BoardExampleIndexLazyRoute,
  TodoExampleIndexLazyRoute: TodoExampleIndexLazyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
