/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

import { Route as rootRouteImport } from './routes/__root';
import { Route as AboutNotLazyRouteImport } from './routes/aboutNotLazy';
import { Route as IndexRouteImport } from './routes/index';
import { Route as TodoTodoidRouteImport } from './routes/todo/$todoid';

const AboutLazyRouteImport = createFileRoute('/about')();
const TodoIndexLazyRouteImport = createFileRoute('/todo/')();

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route));
const AboutNotLazyRoute = AboutNotLazyRouteImport.update({
  id: '/aboutNotLazy',
  path: '/aboutNotLazy',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const TodoIndexLazyRoute = TodoIndexLazyRouteImport.update({
  id: '/todo/',
  path: '/todo/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/todo/index.lazy').then((d) => d.Route));
const TodoTodoidRoute = TodoTodoidRouteImport.update({
  id: '/todo/$todoid',
  path: '/todo/$todoid',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/aboutNotLazy': typeof AboutNotLazyRoute;
  '/about': typeof AboutLazyRoute;
  '/todo/$todoid': typeof TodoTodoidRoute;
  '/todo': typeof TodoIndexLazyRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/aboutNotLazy': typeof AboutNotLazyRoute;
  '/about': typeof AboutLazyRoute;
  '/todo/$todoid': typeof TodoTodoidRoute;
  '/todo': typeof TodoIndexLazyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/aboutNotLazy': typeof AboutNotLazyRoute;
  '/about': typeof AboutLazyRoute;
  '/todo/$todoid': typeof TodoTodoidRoute;
  '/todo/': typeof TodoIndexLazyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/aboutNotLazy' | '/about' | '/todo/$todoid' | '/todo';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/aboutNotLazy' | '/about' | '/todo/$todoid' | '/todo';
  id: '__root__' | '/' | '/aboutNotLazy' | '/about' | '/todo/$todoid' | '/todo/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutNotLazyRoute: typeof AboutNotLazyRoute;
  AboutLazyRoute: typeof AboutLazyRoute;
  TodoTodoidRoute: typeof TodoTodoidRoute;
  TodoIndexLazyRoute: typeof TodoIndexLazyRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/aboutNotLazy': {
      id: '/aboutNotLazy';
      path: '/aboutNotLazy';
      fullPath: '/aboutNotLazy';
      preLoaderRoute: typeof AboutNotLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/todo/': {
      id: '/todo/';
      path: '/todo';
      fullPath: '/todo';
      preLoaderRoute: typeof TodoIndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/todo/$todoid': {
      id: '/todo/$todoid';
      path: '/todo/$todoid';
      fullPath: '/todo/$todoid';
      preLoaderRoute: typeof TodoTodoidRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutNotLazyRoute: AboutNotLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  TodoTodoidRoute: TodoTodoidRoute,
  TodoIndexLazyRoute: TodoIndexLazyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
