#!/bin/sh
echo "🔵 Running pre-push hook..."

yarn pre-push

if [ $? -ne 0 ]; then
  echo "❌ Pre-push checks failed. Please fix the errors before pushing."
  exit 1
fi

echo "✅ pre-push hook completed"